<?php

/**
 * TeamPlayersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeamPlayersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeamPlayersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TeamPlayers');
    }
}